dict1 = {
"IDBRBK": "Boise-River/banner-knob",
"IDBRBS": "Boise-River/banner-snotel",
"IDBRBO": "Boise-River/banner-open",
"IDBRK2": "Boise-River/mores-creek", #change me
"IDBRMM": "Boise-River/bogus-mores-mtn",
"IDBRBL": "Boise-River/bogus-lower",
"IDBRBT": "Boise-River/bogus-lower-trees",
"IDBRLO": "Boise-River/LDP-open",
"IDBRLT": "Boise-River/LDP-tree",
"UTLCAC": "Little-Cottonwood-Canyon/alta-collins",
"UTLCAW": "Little-Cottonwood-Canyon/atwater",
"COGMSO": "Grand-Mesa/grand-mesa", #change me
"MTARP1": "Central-Ag/snowex-1", #change me
"MTARP2": "Central-Ag/wx", #change me
"MTARP3": "Central-Ag/wheat", #change me
"COCPCP": "Cameron-Pass/cameron-peak",
"COCPMR": "Cameron-Pass/michigan-river",
"COSBSA": "Senator-Beck/swamp-angel",
"COFEJ1": "Fraser/jpl-1",
"COFFJ1": "Fraser/jpl-1",
"COFEJ2": "Fraser/jpl-2",
"COFFJ2": "Fraser/jpl-2",
"COFEB1": "Fraser/snowex-b-1",
"COFFB1": "Fraser/snowex-b-1",
"COFEB2": "Fraser/snowex-b-2",
"COFFB2": "Fraser/snowex-b-2",
"COFS01": "Fraser/st-louis",
"COFS02": "Fraser/st-louis",
"COFS03": "Fraser/st-louis",
"COFS04": "Fraser/st-louis",
"COFS05": "Fraser/st-louis",
"COFS06": "Fraser/st-louis",
"COFS07": "Fraser/st-louis",
"COFS08": "Fraser/st-louis",
"COFS09": "Fraser/st-louis",
"COFS10": "Fraser/st-louis",
"COFS11": "Fraser/st-louis",
"COFS12": "Fraser/st-louis",
"COFS13": "Fraser/st-louis",
"COFS14": "Fraser/st-louis",
"COFS15": "Fraser/st-louis",
"COFS16": "Fraser/st-louis",
"COFS17": "Fraser/st-louis",
"COFF01": "Fraser/fool-creek",
"COFF02": "Fraser/fool-creek",
"COFF03": "Fraser/fool-creek",
"COFF04": "Fraser/fool-creek",
"COFF05": "Fraser/fool-creek",
"COFF06": "Fraser/fool-creek",
"COFF07": "Fraser/fool-creek",
"COFF08": "Fraser/fool-creek",
"COFF09": "Fraser/fool-creek",
"COFF10": "Fraser/fool-creek",
"COFF11": "Fraser/fool-creek",
"COFF12": "Fraser/fool-creek",
"COFF13": "Fraser/fool-creek",
"COFF14": "Fraser/fool-creek",
"COFF15": "Fraser/fool-creek",
"COFF16": "Fraser/fool-creek",
"COFF17": "Fraser/fool-creek"
}
